### ISSUE TITLE
Tags, NEWS and releases?

### ISSUE THREAD

**Issue by sckott** [ropensci/rAvis#18]
Hi all, Would you mind maintaining a `NEWS` (or `NEWS.md`) file in the package, and using GitHub releases?   

The NEWS file is used to highlight major changes/updates/bug fixes in each new version sent to CRAN. An example: https://github.com/ropensci/taxize/blob/master/NEWS.md

Releases are a formal way to associate changes with a particular git tag. If you can assign a git tag to each version you send to CRAN, e.g. https://github.com/ropensci/taxize/tree/v0.6.0 then on the releases page for your repo, you can paste in the corresponding news items for that version, like this https://github.com/ropensci/taxize/releases/tag/v0.6.0

This is a all good practice, and will help users quickly determine what things have changed in each new version.

**Comment by SaraVarela** [comment]
Hi Scott!

Yes. Sure. We will do it. I think we already had tags for the versions of the packages that we used in the publications.
We did not add new functions to rAvis, it was just a small fix because the layout of the Web changed and some functions were not working anymore.

Best,
Sara

**Comment by sckott** [comment]
> I think we already had tags for the versions of the packages that we used in the publications.

right, there is one tag under tags for this repo https://github.com/ropensci/rAvis/tree/v0.1

if not too much trouble, would really appreciate it, thanks!

**Comment by SaraVarela** [comment]
Done! 
:-) 

we did new tags and news for paleobioDB and for rAvis. 

thanks for your nice suggestions, 
cheers
Sara
