### ISSUE TITLE
CRAN check issues

### ISSUE THREAD

**Issue by sckott** [ropensci/rAvis#19]
there's a few issues that CRAN checks reveal https://cran.rstudio.com/web/checks/check_results_rAvis.html none are fatal, but things to tidy up

**Comment by sckott** [comment]
@SaraVarela any thoughts

**Comment by SaraVarela** [comment]
Hi @sckott I changed the namespace yesterday to solve those notes... let's see what happened

**Comment by sckott** [comment]
do you mean the NAMESPACE file?

**Comment by SaraVarela** [comment]
yes

**Comment by sckott** [comment]
that won't help on travis though since you need to tell it to install the C libraries for gdal

**Comment by SaraVarela** [comment]
I see. I do not know how to do this. Any advice/hint? :-)

**Comment by sckott** [comment]
here's an example of what should work https://github.com/ropensci/rseaaroundus/blob/master/.travis.yml

**Comment by maelle** [comment]
Any help needed with this @SaraVarela?

**Comment by maelle** [comment]
Ok will have a look soon!
