### ISSUE TITLE
Repo topics

### ISSUE THREAD

**Issue by maelle** [ropensci/rAvis#24]
:wave: @SaraVarela!

I added a few repo topics

![image](https://user-images.githubusercontent.com/8360597/40724571-a3c19e3c-6421-11e8-8994-9d5f77dfa81d.png)

Feel free to edit but I'd recommend keeping "r" and "rstats".

**Comment by SaraVarela** [comment]
Hi @maelle cool! :-)

**Comment by maelle** [comment]
Thanks!
