### ISSUE TITLE
Question about the data source

### ISSUE THREAD

**Issue by maelle** [ropensci/rAvis#25]
@SaraVarela out of curiosity, is the data collected in proyecto Avis fed into another data collection, e.g. eBird/GBIF?

**Comment by SaraVarela** [comment]
Hi @maelle 
nope. proyecto Avis is old, it started in 2005, and at that time there was no GBIF (or they did not know it). so far, we did not talk to the Spanish GBIF node to be included as an official source of data, nor to eBird. But, yup, it might be nice to do it :-)

**Comment by SaraVarela** [comment]
so, it is an independent database, where bird watchers can upload their records, and in 2005 there was no other web service to do so in Spain, and there are older records because people uploaded their personal observation books.

**Comment by maelle** [comment]
Thank you! 👌
